### ISSUE TITLE
Crash when the annotation class isn't exists in runtime

### ISSUE THREAD

**Issue by SettingDust** [Bawnorton/MixinSquared#11]
```
Caused by: java.lang.ClassNotFoundException: javax.annotation.Nullable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_381]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_381]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_381]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_381]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_381]
	at settingdust.backport2768.mixinsquared.adjuster.tools.AdjustableAnnotationNode$KnownAnnotations$1.getAnnotationClass(AdjustableAnnotationNode.java:146) ~[AdjustableAnnotationNode$KnownAnnotations$1.class:?]
	at settingdust.backport2768.mixinsquared.adjuster.tools.AdjustableAnnotationNode.<init>(AdjustableAnnotationNode.java:53) ~[AdjustableAnnotationNode.class:?]
	at settingdust.backport2768.mixinsquared.adjuster.tools.AdjustableAnnotationNode$KnownAnnotations$1.<init>(AdjustableAnnotationNode.java:142) ~[AdjustableAnnotationNode$KnownAnnotations$1.class:?]
	at settingdust.backport2768.mixinsquared.adjuster.tools.AdjustableAnnotationNode$KnownAnnotations.fromNode(AdjustableAnnotationNode.java:142) ~[AdjustableAnnotationNode$KnownAnnotations.class:?]
	at settingdust.backport2768.mixinsquared.adjuster.tools.AdjustableAnnotationNode.fromNode(AdjustableAnnotationNode.java:64) ~[AdjustableAnnotationNode.class:?]
```

**Comment by Bawnorton** [comment]
Right, Nullable is not always present in a given ide.

**Comment by Bawnorton** [comment]
Fixed in beta.4
