### ISSUE TITLE
Mixin targets are nonfunctional 

### ISSUE THREAD

**Issue by QPCrummer** [Bawnorton/MixinSquared#5]
Mixins such as Injects, Redirects, and ModifyArg can only use the "HEAD" or "TAIL" targets, but cannot use "INVOKE" with a custom target. 
I'm using version 0.1.1 of Mixin Squared.

For example, I was trying to mixin into one of Lithium's Mixins with the following code:
```java
@Mixin(value = HopperBlockEntity.class, priority = 1500, remap = false)
public abstract class LithiumHopperCompatMixin {
    @TargetHandler(
            mixin = "me.jellysquid.mods.lithium.mixin.block.hopper.HopperBlockEntityMixin",
            name = "lithiumExtract",
            prefix = "handle"
    )
    @ModifyArg(
            method = "@MixinSquared:Handler",
            at = @At(value = "INVOKE", target = "Lnet/minecraft/item/ItemStack;increment(I)V"),
            index = 0
    )
    private static int injectedItem(int x) {
        return Main.items;
    }  
```

All of the targets are correct, however this error is produced in the log:
```
[23:59:19] [main/INFO] (FabricLoader/MixinExtras|Service) Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[23:59:21] [main/ERROR] (FabricLoader/Mixin) Mixin apply for mod hopperspeedsim failed hopperspeedsimulator.mixins.json:LithiumHopperCompatMixin from mod hopperspeedsim -> net.minecraft.block.entity.HopperBlockEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyArg annotation on injectedItem could not find any targets matching '@MixinSquared:Handler[mixin='me.jellysquid.mods.lithium.mixin.block.hopper.HopperBlockEntityMixin', name='lithiumExtract', prefix='handle']' in net.minecraft.block.entity.HopperBlockEntity. No refMap loaded. [PREINJECT Applicator Phase -> hopperspeedsimulator.mixins.json:LithiumHopperCompatMixin from mod hopperspeedsim -> Prepare Injections ->  -> modify$zzl000$hopperspeedsim$injectedItem(I)I -> Parse]
 org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyArg annotation on injectedItem could not find any targets matching '@MixinSquared:Handler[mixin='me.jellysquid.mods.lithium.mixin.block.hopper.HopperBlockEntityMixin', name='lithiumExtract', prefix='handle']' in net.minecraft.block.entity.HopperBlockEntity. No refMap loaded. [PREINJECT Applicator Phase -> hopperspeedsimulator.mixins.json:LithiumHopperCompatMixin from mod hopperspeedsim -> Prepare Injections ->  -> modify$zzl000$hopperspeedsim$injectedItem(I)I -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.ModifyArgInjectionInfo.<init>(ModifyArgInjectionInfo.java:45) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:563) ~[minecraft-merged-91cd4aea83-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.block.FireBlock.registerDefaultFlammables(FireBlock.java:336) ~[minecraft-merged-91cd4aea83-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:54) ~[minecraft-merged-91cd4aea83-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:170) ~[minecraft-merged-91cd4aea83-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
	```

**Comment by Bawnorton** [comment]
You have `remap = false` in your mixin annotation but are referencing a minecraft class in your injection point target, injectors inherit remapping from the mixin annotation and injection points inherit from the injector.
Remove the `remap = false`

**Comment by Bawnorton** [comment]
Also your prefix is wrong, you want `handler`

**Comment by QPCrummer** [comment]
Thank you so much, I guess I just glossed over the fact that it was `handle` and not `handler`. Everything works as expected now! This is a great piece of software, thanks for making it.
